### ISSUE TITLE
[Suggestion] Hide use of dry-types with a custom "Types" module

### ISSUE THREAD

**Issue by AMHOL** [runtastic/request_handler#25]
Hi, I was discussing your project with @ahmgeek on Gitter and I suggested that you should hide the dry-* libraries behind your own interfaces, the suggestion for dry-types was:

Rather than:

```ruby
include_options do
  allowed Dry::Types["strict.string"].enum("comments", "author")
end
```

You could just define your own types module, e.g.:

```ruby
module RequestHandler
  module Types
    include Dry::Types.module

    # You can also define custom types here
  end
end
```

And it would become:

```ruby
include_options do
  allowed Types["strict.string"].enum("comments", "author")
end
```

**Comment by andreaseger** [comment]
If you integrate this within your app you probably also use dry-types elsewhere(because why wouldn't you) and one can just create a top-level `Types` module with dry-types and reuse the types from there. At least that's how we use it in our apps.

So one would have this somewhere with the build-in types and all custom types:

```ruby
module Types
  include Dry::Types.module

  # custom types you'd use throughout your application
end
```

and in the request_handlers you'd simply reuse them
```ruby
include_options do
  allowed Types::Strict::String.enum("comments", "author")
end
```

by having another `Types` module in `RequestHandler` it would just cause confusion which types are used especially when you add custom types in your application.
